### PR TITLE
Feature: Make `Money`, `Currency` and `ExchangeRate` classes natively JSON serializable

### PR DESCRIPTION
**Pull request by marcelomendoncasoares**
Overview
---
I've been frequently using the `money` package to store values that needs to be persisted in a database or sent to some endpoint and, thus, need to serialize the classes. In all these applications, I end up writing a similar logic to serialize these objects, but it is sometimes hard to achieve without having to write other classes just to store the value, as the `Money` class is sealed. It would be much more convenient if the classes are natively (and safely) JSON serializable, which is why I'm opening this pull request.

Changes
---
- Add `fromJson` and `toJson` methods to `Money`, `Currency` and `ExchangeRate` classes.
- Add tests for all serialization/deserialization methods.

Additional Notes
---
When serializing the `Fixed` values for `Money` and `ExchangeRate`, the stored value will generate two keys: one for the `minorUnits` in `double` and the other for the `scale` as `int`. This choice is to preserve the integrity of the number, as it is not possible to save `BigInt` directly to Json and the serialization could end up truncating the values if saved as `int`. Despite `double` not being adequate for handling money, in this case there is no problem as the `Fixed.minorUnits` will always be a round number, only saved as `double` because of the range of this type on all languages. No fractional values will be saved as double, which could lead to lost in precision.

This update does not alter in any way the behavior of the classes, only adding the serialization/deserialization methods.

### CODE REVIEW

**Comment by bsutton** [comment]
thanks for the PR. I'm not in love with using double. Can we not just use a string?

**Comment by marcelomendoncasoares** [comment]
My mais reason to go with `double` instead of `string` was to allow for filtering or comparing the serialized values. If we are to store it on a database or any other place where we can filter results, using a numerical value can be used alongside the scale to perform calculations, and will occupy less space than storing strings.

**Comment by bsutton** [comment]
so my next question is, given we are dealing with money do we really expect to see a value bigger than int64?

bit coin uses 8 digits which leaves 11 digits for the int part or 100,000,000,000 or 100 billion bit coins. There is a max of 21 million bit coins.

for standard usd that is 100,000,000,000,000,000.00  or 100,000 trillion. Total private net wealth of the world is 454 trillion.

**Comment by bsutton** [comment]
In fact the largest number a double can store is 2^53, so now I think about it we should just be using an int64 as a double gives us no advantage.

**Comment by bsutton** [comment]
The json spec doesn't actually put a limit on the size of an int but for practical matters it looks like 2^53 is the upper limit - as javascript doesn't support ints only doubles.

So I'm still inclined to think there is no value in using a double. We just store it as an int (by converting the bigint to a string but not quoting the json value).  The correct handling of values larger than 2^64 is then up to the end that parses these values.

The likes of mysql is also limited to 2^64 so if a user wants to store a large value then they are going to probably store it as a string anyway.

**Comment by marcelomendoncasoares** [comment]
Your argument is totally right and gave me a better idea of how to serialize the `amount` as number without needing `double` and ensuring precision for valid money values. Instead of storing `Fixed.minorUnits`, which can get bigger than integer due to the scale of the currency, I changed to store the `amount` as separate `Fixed.integerPart` and `Fixed.decimalPart`, both as integers. The reconstruction can be safely performed concatenating them as a `decimal` string and this even facilitates numeric comparisons later on the serialized values. To ensure no lost in precision, I added a test with your example of a very large money number.

What do you think of this approach?

**Comment by bsutton** [comment]
I'm wondering if we should add leading zeros to the decimalPart.

e.g. scale 4
10.0002

is written to json as:

amountIntegerPart: 10
amountDecimalPart: 0002

Whilst what you have done will work, I wonder if the above formatting would make the json easier for a human to read?

Also are we been overly verbose with the key names?

could we just use:
integer: 10
decimal: 0002
scale:  4

I'm also wondering if we should use decimals rather than scale, so maybe:

integerPart: 10
decimalPart: 0002
decimals:  4
isoCode: AUD

I'm not hung up on any of these changes, just throwing some ideas out there.  I will let you decided.

Otherwise I'm happy to merge.

**Comment by bsutton** [comment]
can we add a test with a scale of say 10 just check the extreme end of large numbers of decimals.

**Comment by bsutton** [comment]
just saw the formatting for the exchange rate:

  /// instance using the [ExchangeRate.fromJson] factory.
  Map<String, dynamic> toJson() => {
        'exchangeRateIntegerPart': exchangeRate.integerPart.toInt(),
        'exchangeRateDecimalPart': exchangeRate.decimalPart.toInt(),
        'decimalDigits': exchangeRate.scale,
        'fromIsoCode': fromCurrency.isoCode,
        'toIsoCode': toCurrency.isoCode,
        'toDecimalDigits': toDecimalDigits,
      };

we should be consistent on naming conventions between the twol.

**Comment by marcelomendoncasoares** [comment]
> I'm wondering if we should add leading zeros to the decimalPart.
> 
> e.g. scale 4 10.0002
> 
> is written to json as:
> 
> amountIntegerPart: 10 amountDecimalPart: 0002
> 
> Whilst what you have done will work, I wonder if the above formatting would make the json easier for a human to read?
> 
> Also are we been overly verbose with the key names?
> 
> could we just use: integer: 10 decimal: 0002 scale: 4
> 
> I'm also wondering if we should use decimals rather than scale, so maybe:
> 
> integerPart: 10 decimalPart: 0002 decimals: 4 isoCode: AUD
> 
> I'm not hung up on any of these changes, just throwing some ideas out there. I will let you decided.
> 
> Otherwise I'm happy to merge.

Just simplified the key names - they were indeed more verbose than necessary - and standardized between `Money` and `ExchangeRate`. And I agree that adding leading zeros to the decimal part would make the JSON more human-readable, but I think it would add too much complexity with no benefits from the code perspective. In the end, the decoded values would lose the leading zeros, as they are integers. Otherwise, because `toJson` return a Map - not the JSON string itself - we would need to have `integerPart` as integer and `decimalPart` as string, which wouldn't make much sense.

> can we add a test with a scale of say 10 just check the extreme end of large numbers of decimals.

I made one already with the scale of 12. Do you think we need another?

image

**Comment by bsutton** [comment]
released as 5.4.0.

Greatly appreciate your work!!!

**Comment by marcelomendoncasoares** [comment]
Thanks a lot! It was a pleasure to contribute!!

**Pull request merged**
